<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/Getting_Financial_Data_Google_Finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [6]:
import pandas as pd
import numpy as np
import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [3]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()

print(start)
print(end)

2015-01-01 00:00:00
2024-11-16 13:19:12.215309

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [4]:
stocks = ['AAPL', 'TSLA', 'TWTR', 'IBM', 'LNKD']

### Step 4. Read the data from google, assign to df and print it

In [10]:
import yfinance as yf
from pandas_datareader import data as web

df = yf.download(stocks, start="2024-01-01", end="2024-11-16")
df

[*********************100%***********************]  5 of 5 completed
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['TWTR']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
ERROR:yfinance:['LNKD']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-01-01 -> 2024-11-16)')

Price                       Adj Close                                    \
Ticker                           AAPL         IBM LNKD        TSLA TWTR
Date
2024-01-02 00:00:00+00:00  184.734970  155.865463  NaN  248.419998  NaN
2024-01-03 00:00:00+00:00  183.351746  154.514328  NaN  238.449997  NaN
2024-01-04 00:00:00+00:00  181.023163  155.247803  NaN  237.929993  NaN
2024-01-05 00:00:00+00:00  180.296722  153.607132  NaN  237.490005  NaN
2024-01-08 00:00:00+00:00  184.655365  155.518021  NaN  240.449997  NaN
...                               ...         ...  ...         ...  ...
2024-11-11 00:00:00+00:00  224.229996  211.900009  NaN  350.000000  NaN
2024-11-12 00:00:00+00:00  224.229996  210.860001  NaN  328.489990  NaN
2024-11-13 00:00:00+00:00  225.119995  210.919998  NaN  330.239990  NaN
2024-11-14 00:00:00+00:00  228.220001  208.990005  NaN  311.179993  NaN
2024-11-15 00:00:00+00:00  225.000000  204.990005  NaN  320.720001  NaN

Price                           Close                                    ...  \
Ticker                           AAPL         IBM LNKD        TSLA TWTR  ...
Date                                                                     ...
2024-01-02 00:00:00+00:00  185.639999  161.500000  NaN  248.419998  NaN  ...
2024-01-03 00:00:00+00:00  184.250000  160.100006  NaN  238.449997  NaN  ...
2024-01-04 00:00:00+00:00  181.910004  160.860001  NaN  237.929993  NaN  ...
2024-01-05 00:00:00+00:00  181.179993  159.160004  NaN  237.490005  NaN  ...
2024-01-08 00:00:00+00:00  185.559998  161.139999  NaN  240.449997  NaN  ...
...                               ...         ...  ...         ...  ...  ...
2024-11-11 00:00:00+00:00  224.229996  213.570007  NaN  350.000000  NaN  ...
2024-11-12 00:00:00+00:00  224.229996  210.860001  NaN  328.489990  NaN  ...
2024-11-13 00:00:00+00:00  225.119995  210.919998  NaN  330.239990  NaN  ...
2024-11-14 00:00:00+00:00  228.220001  208.990005  NaN  311.179993  NaN  ...
2024-11-15 00:00:00+00:00  225.000000  204.990005  NaN  320.720001  NaN  ...

Price                            Open                                    \
Ticker                           AAPL         IBM LNKD        TSLA TWTR
Date
2024-01-02 00:00:00+00:00  187.149994  162.830002  NaN  250.080002  NaN
2024-01-03 00:00:00+00:00  184.220001  161.000000  NaN  244.979996  NaN
2024-01-04 00:00:00+00:00  182.149994  160.220001  NaN  239.250000  NaN
2024-01-05 00:00:00+00:00  181.990005  159.910004  NaN  236.860001  NaN
2024-01-08 00:00:00+00:00  182.089996  158.690002  NaN  236.139999  NaN
...                               ...         ...  ...         ...  ...
2024-11-11 00:00:00+00:00  225.000000  214.399994  NaN  346.299988  NaN
2024-11-12 00:00:00+00:00  224.550003  211.899994  NaN  342.739990  NaN
2024-11-13 00:00:00+00:00  224.009995  209.500000  NaN  335.850006  NaN
2024-11-14 00:00:00+00:00  225.020004  210.000000  NaN  327.690002  NaN
2024-11-15 00:00:00+00:00  226.399994  207.460007  NaN  310.570007  NaN

Price                        Volume
Ticker                         AAPL      IBM LNKD       TSLA TWTR
Date
2024-01-02 00:00:00+00:00  82488700  3825000  NaN  104654200  NaN
2024-01-03 00:00:00+00:00  58414500  4086100  NaN  121082600  NaN
2024-01-04 00:00:00+00:00  71983600  3212000  NaN  102629300  NaN
2024-01-05 00:00:00+00:00  62303300  4199400  NaN   92379400  NaN
2024-01-08 00:00:00+00:00  59144500  3321700  NaN   85166600  NaN
...                             ...      ...  ...        ...  ...
2024-11-11 00:00:00+00:00  42005600  3013000  NaN  210521600  NaN
2024-11-12 00:00:00+00:00  40398300  2817800  NaN  155726000  NaN
2024-11-13 00:00:00+00:00  48566200  3247800  NaN  125405600  NaN
2024-11-14 00:00:00+00:00  44923900  6372900  NaN  120726100  NaN
2024-11-15 00:00:00+00:00  47832200  3982800  NaN  114128900  NaN

[222 rows x 30 columns]

### Step 5.  What is the type of structure of df ?

In [11]:
type(df)

pandas.core.frame.DataFrame

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

In [12]:
df.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close',  'IBM'),
            ('Adj Close', 'LNKD'),
            ('Adj Close', 'TSLA'),
            ('Adj Close', 'TWTR'),
            (    'Close', 'AAPL'),
            (    'Close',  'IBM'),
            (    'Close', 'LNKD'),
            (    'Close', 'TSLA'),
            (    'Close', 'TWTR'),
            (     'High', 'AAPL'),
            (     'High',  'IBM'),
            (     'High', 'LNKD'),
            (     'High', 'TSLA'),
            (     'High', 'TWTR'),
            (      'Low', 'AAPL'),
            (      'Low',  'IBM'),
            (      'Low', 'LNKD'),
            (      'Low', 'TSLA'),
            (      'Low', 'TWTR'),
            (     'Open', 'AAPL'),
            (     'Open',  'IBM'),
            (     'Open', 'LNKD'),
            (     'Open', 'TSLA'),
            (     'Open', 'TWTR'),
            (   'Volume', 'AAPL'),
            (   'Volume',  'IBM'),
            (   'Volume', 'LNKD'),
            (   'Volume', 'TSLA'),
            (   'Volume', 'TWTR')],
           names=['Price', 'Ticker'])

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

In [13]:
vol = df['Volume']
vol

Ticker                         AAPL      IBM  LNKD       TSLA  TWTR
Date
2024-01-02 00:00:00+00:00  82488700  3825000   NaN  104654200   NaN
2024-01-03 00:00:00+00:00  58414500  4086100   NaN  121082600   NaN
2024-01-04 00:00:00+00:00  71983600  3212000   NaN  102629300   NaN
2024-01-05 00:00:00+00:00  62303300  4199400   NaN   92379400   NaN
2024-01-08 00:00:00+00:00  59144500  3321700   NaN   85166600   NaN
...                             ...      ...   ...        ...   ...
2024-11-11 00:00:00+00:00  42005600  3013000   NaN  210521600   NaN
2024-11-12 00:00:00+00:00  40398300  2817800   NaN  155726000   NaN
2024-11-13 00:00:00+00:00  48566200  3247800   NaN  125405600   NaN
2024-11-14 00:00:00+00:00  44923900  6372900   NaN  120726100   NaN
2024-11-15 00:00:00+00:00  47832200  3982800   NaN  114128900   NaN

[222 rows x 5 columns]

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

In [15]:
vol['week'] = vol.index.isocalendar().week
vol['year'] = vol.index.isocalendar().year

week = vol.groupby(['week','year']).sum()
week.head()

<ipython-input-15-5e66b3a88383>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vol['week'] = vol.index.isocalendar().week
<ipython-input-15-5e66b3a88383>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vol['year'] = vol.index.isocalendar().year

Ticker          AAPL       IBM  LNKD       TSLA  TWTR
week year
1    2024  275190100  15322500   0.0  420745500   0.0
2    2024  238352300  17641300   0.0  502263400   0.0
3    2024  259667200  19860900   0.0  429210600   0.0
4    2024  255536900  57499400   0.0  653348300   0.0
5    2024  325876200  28282700   0.0  540565200   0.0

### Step 9. Find all the volume traded in the year of 2015

In [23]:
# Extract the year from the index
vol['year'] = vol.index.year

# Use .loc to filter the data for 2015
vol_2015 = vol.loc[vol['year'] == 2015]

# Group by 'year' and sum the volume for 2015
year_2015 = vol_2015.groupby('year').sum()

# Print the total volume for 2015
print(year_2015)

Empty DataFrame
Columns: [AAPL, IBM, LNKD, TSLA, TWTR, week]
Index: []

<ipython-input-23-de0e91b4e0f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vol['year'] = vol.index.year

### BONUS: Create your own question and answer it.