<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/US_Baby_Names.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```

# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [4]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [5]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [6]:
baby_names.drop(['Unnamed: 0','Id'],axis=1,inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [7]:
baby_names.Gender.value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [8]:
baby_names.groupby('Name').sum()

,Year,Gender,State,Count
Name,,,,
Aaban,4027,MM,NYNY,12
Aadan,8039,MMMM,CACACATX,23
Aadarsh,2009,M,IL,5
Aaden,393963,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,ALALALALALALALARARARAZAZAZAZAZAZCACACACACACACA...,3426
Aadhav,2014,M,CA,6
...,...,...,...,...
Zyra,14085,FFFFFFF,CACACAFLTXTXTX,42
Zyrah,4024,FF,CATX,11
Zyren,2013,M,TX,6
Zyria,20089,FFFFFFFFFF,GAGAGALALALATXTXTXTX,59
Zyriah,18087,FFFFFFFFF,GAGALATXTXTXTXTXTX,58

### Step 8. How many different names exist in the dataset?

In [9]:
baby_names.Name.nunique()

17632

### Step 9. What is the name with most occurrences?

In [10]:
baby_names.Name.value_counts().head(1)

Name
Riley    1112
Name: count, dtype: int64

### Step 10. How many different names have the least occurrences?

In [13]:
baby_names.Name.value_counts().tail()

Name
Terryn     1
Yanna      1
Zemirah    1
Emmilyn    1
Coalton    1
Name: count, dtype: int64

### Step 11. What is the median name occurrence?

In [14]:
baby_names.Name.value_counts().median()

8.0

### Step 12. What is the standard deviation of names?

In [15]:
baby_names.Name.value_counts().std()

122.02996350814088

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [16]:
baby_names.describe()

               Year         Count
count  1.016395e+06  1.016395e+06
mean   2.009053e+03  3.485012e+01
std    3.138293e+00  9.739735e+01
min    2.004000e+03  5.000000e+00
25%    2.006000e+03  7.000000e+00
50%    2.009000e+03  1.100000e+01
75%    2.012000e+03  2.600000e+01
max    2.014000e+03  4.167000e+03