<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/WindStatistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [ ]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data',sep='\s+',parse_dates=[[0,1,2]])
data.head()

<ipython-input-2-20e136fbb23c>:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data',sep='\s+',parse_dates=[[0,1,2]])
<ipython-input-2-20e136fbb23c>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data',sep='\s+',parse_dates=[[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [3]:
data['Yr_Mo_Dy']=pd.to_datetime(data['Yr_Mo_Dy'])

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [4]:
data.set_index('Yr_Mo_Dy',inplace=True)
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [5]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [6]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [7]:
data.mean().mean()

10.227982360836938

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days

#### A different set of numbers for each location.

In [8]:
loc_stats=data.describe()
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [9]:
day_stats=data.apply(lambda x:x.describe())
day_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [10]:
data[data.index.month==1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [11]:
data.groupby(data.index.to_period('A')).mean()

<ipython-input-11-ec8e558586bc>:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'Y' instead.
  data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370
2061,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
2062,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
2063,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
2064,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
2065,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
2066,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
2067,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
2068,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
2069,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
2070,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
2071,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
2072,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
2073,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096

### Step 13. Downsample the record to a monthly frequency for each location.

In [12]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1974-01,20.990968,17.623548,17.514839,10.549355,15.858387,11.298387,14.112258,12.786452,14.691935,15.092903,19.929677,24.573226
1974-02,13.576071,12.451786,11.263571,6.103929,10.590357,6.516429,9.818929,8.578929,9.212857,9.045000,12.172143,16.891786
1974-03,11.156129,10.725484,12.019355,5.743226,9.576452,5.892903,8.520000,9.039032,8.339032,7.626774,11.234516,15.141613
1974-04,9.481000,6.919667,12.099333,4.061000,7.659000,4.046333,5.438667,7.609333,6.058667,5.024000,7.983333,9.898000
1974-05,13.381290,11.769677,12.355484,6.656452,10.874194,6.481290,9.680645,10.810645,8.830323,9.624516,13.319032,16.006774
...,...,...,...,...,...,...,...,...,...,...,...,...
2073-08,8.955161,7.868710,8.996774,4.396129,7.860645,4.989355,6.051290,5.173548,6.171935,5.745161,10.512258,12.328710
2073-09,11.632667,10.963667,11.634667,5.194333,9.100333,5.730667,7.053000,7.048333,6.911667,6.111667,12.149667,13.966667
2073-10,11.531935,9.858710,11.535161,4.356452,8.773226,5.189677,6.455806,7.140000,6.254516,6.890323,10.758387,14.955484
2073-11,11.540667,10.868000,10.613000,5.385000,10.463667,6.147333,7.525667,7.619667,8.378333,8.311333,11.499333,18.441000
2073-12,13.670000,12.086774,11.278065,5.619355,10.672581,6.914516,10.841290,8.516129,9.311613,9.702581,13.274194,19.728387

### Step 14. Downsample the record to a weekly frequency for each location.

In [13]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1973-12-31/1974-01-06,23.655000,16.278333,20.560000,12.075000,15.348333,12.673333,12.596667,12.833333,16.118333,17.248333,18.036667,24.450000
1974-01-07/1974-01-13,21.450000,19.514286,17.290000,11.137143,17.608571,11.971429,14.857143,13.392857,14.938571,15.547143,22.870000,25.210000
1974-01-14/1974-01-20,21.335714,19.190000,16.964286,9.992857,17.074286,11.382857,15.731429,13.565714,14.878571,14.397143,21.941429,26.510000
1974-01-21/1974-01-27,17.612857,15.737143,14.915714,8.802857,13.285714,9.658571,12.470000,11.328571,12.655714,12.832857,16.857143,20.892857
1974-01-28/1974-02-03,20.007143,16.865714,17.445714,10.608571,15.530000,10.611429,14.541429,12.344286,14.465714,14.528571,17.280000,23.570000
...,...,...,...,...,...,...,...,...,...,...,...,...
2073-11-27/2073-12-03,11.661429,10.261429,10.628571,4.364286,9.871429,5.492857,7.125714,7.052857,6.977143,5.842857,10.535714,14.047143
2073-12-04/2073-12-10,15.694286,12.995714,12.791429,6.320000,11.505714,8.112857,11.882857,9.108571,9.885714,10.530000,13.750000,20.047143
2073-12-11/2073-12-17,16.344286,14.101429,11.411429,8.208571,13.975714,8.802857,15.197143,11.102857,12.381429,13.410000,16.552857,26.521429
2073-12-18/2073-12-24,12.392857,11.960000,10.768571,3.892857,8.131429,3.692857,6.232857,5.584286,6.428571,6.214286,8.862857,13.075714
2073-12-25/2073-12-31,11.060000,10.392857,10.272857,4.714286,9.727143,7.328571,10.298571,8.632857,9.340000,9.744286,14.678571,20.182857

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [14]:
data.resample('W').agg(['min','max','mean','std']).iloc[1:53, :].head()

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1974-01-13   6.50  28.75  21.450000  7.927883  10.63  26.63  19.514286
1974-01-20  15.83  31.75  21.335714  5.546912  15.87  24.33  19.190000
1974-01-27  11.17  24.75  17.612857  5.584069  10.54  21.96  15.737143
1974-02-03  13.88  27.58  20.007143  4.797293  13.33  20.58  16.865714
1974-02-10   9.25  28.84  18.057143  7.430616   5.46  27.04  16.680000

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1974-01-13  5.906750   6.83  24.58  ...  15.547143  5.458958  13.88  31.08
1974-01-20  3.412277  13.33  23.21  ...  14.397143  1.855170  15.71  26.16
1974-01-27  4.322749   9.79  19.04  ...  12.832857  3.992972   4.67  23.38
1974-02-03  2.801463  11.08  21.29  ...  14.528571  4.931188   9.46  25.96
1974-02-10  7.657600   7.71  23.71  ...  10.862857  5.661059   8.46  27.63

                                   MAL
                 mean       std    min    max       mean       std
Yr_Mo_Dy
1974-01-13  22.870000  6.687992  15.34  32.30  25.210000  6.904979
1974-01-20  21.941429  3.817222  20.62  31.20  26.510000  3.270260
1974-01-27  16.857143  5.842676  10.00  26.87  20.892857  5.512291
1974-02-03  17.280000  5.147252  16.25  38.79  23.570000  7.443895
1974-02-10  16.511429  6.343475  14.09  29.08  20.345714  4.914465

[5 rows x 48 columns]